num1=eval(input('Enter the first number: '))
num2=eval(input('Enter the second number: '))
print('Addition of two numbers is:', num1+num2)
print('Substraction of two numbers is:', num1-num2)
print('Multiplication of two numbers is:', num1*num2)
print('Division of two numbers is:', num1/num2)
